### ISSUE TITLE
setup.py error: no commands supplied

### ISSUE THREAD

**Issue by h6w** [Valodim/pamixer#4]
The readme mentions needing argparse which is enforced, and it should probably mention needing python-setuptools also, since setup.py calls it.

However, even after having installed these tools, I'm still getting:
./setup.py 
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

**Comment by h6w** [comment]
Ah.  Need to specify "install" as in "./setup.py install"

**Comment by arunkumar3234** [comment]
I have the same error need solution ASAP
Thanks In Advance 
Arun

**Comment by kawa0000** [comment]
Install Python 3. and follow following steps:
1. Install pip3 - get-pip.py
2. python3 setup.py build
3. python3 setup.py install
